ALTER TABLE `%prefix%items` ADD `item_type` TINYINT NOT NULL DEFAULT '0' AFTER `item_status`;
ALTER TABLE `%prefix%itemcat` ADD `item_type` TINYINT NOT NULL DEFAULT '0';
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_enable', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_use_captcha', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_use_link_url', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_use_back_link', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_use_descr_full', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_use_meta_keywords', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_use_meta_descr', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_show_dis_cat', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_message', '');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_show_message', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_html_message', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_max_url', '100');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_max_backurl', '100');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_min_title', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_max_title', '100');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_min_email', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_max_email', '100');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_min_descr', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_max_descr', '1024');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_min_descr_full', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_max_descr_full', '2048');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_min_meta_keywords', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_max_meta_keywords', '1024');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_min_meta_descr', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_max_meta_descr', '1024');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_max_cats', '3');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_check_exists_url', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_ignore_www', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_back_link_host', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_check_link', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_auto_approve', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_accept_to_add', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('rss_display', '3');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('rss_show_items', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('rss_title', 'RSS лента для "%TITLE%"');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('rss_descr', 'RSS лента каталога "%CATNAME%"');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('rss_show_child_items', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('rss_items_count', '10');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('rss_item_link', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_use_author', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_min_author', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_article_max_author', '200');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_use_author', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_min_author', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('add_max_author', '200');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('link_new_window', '1');
