CREATE TABLE `%prefix%fields` (`name` varchar(50) NOT NULL default '', `type` tinyint(4) NOT NULL default '0', `active` tinyint(4) NOT NULL default '0', `required` tinyint(4) NOT NULL default '0', `item_type` tinyint(4) NOT NULL default '0', `title` varchar(255) NOT NULL default '', `search` tinyint(4) NOT NULL default '0', `display` varchar(255) NOT NULL default '0', `sort_order` int(11) NOT NULL default '0') ENGINE=MyISAM DEFAULT CHARSET=utf8;
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_int1', 1, 0, 0, 0, 'Integer 1', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_int2', 1, 0, 0, 0, 'Integer 2', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_int3', 1, 0, 0, 0, 'Integer 3', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_double1', 2, 0, 0, 0, 'Float 1', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_double2', 2, 0, 0, 0, 'Float 2', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_double3', 2, 0, 0, 0, 'Float 3', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_varchar1', 3, 0, 0, 0, 'String 1', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_varchar2', 3, 0, 0, 0, 'String 2', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_varchar3', 3, 0, 0, 0, 'String 3', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_datetime1', 4, 0, 0, 0, 'Date 1', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_datetime2', 4, 0, 0, 0, 'Date 2', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_datetime3', 4, 0, 0, 0, 'Date 3', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_text1', 5, 0, 0, 0, 'Text 1', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_text2', 5, 0, 0, 0, 'Text 2', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_text3', 5, 0, 0, 0, 'Text 3', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_int1', 1, 0, 0, 1, 'Integer 1', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_int2', 1, 0, 0, 1, 'Integer 2', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_int3', 1, 0, 0, 1, 'Integer 3', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_double1', 2, 0, 0, 1, 'Float 1', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_double2', 2, 0, 0, 1, 'Float 2', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_double3', 2, 0, 0, 1, 'Float 3', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_varchar1', 3, 0, 0, 1, 'String 1', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_varchar2', 3, 0, 0, 1, 'String 2', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_varchar3', 3, 0, 0, 1, 'String 3', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_datetime1', 4, 0, 0, 1, 'Date 1', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_datetime2', 4, 0, 0, 1, 'Date 2', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_datetime3', 4, 0, 0, 1, 'Date 3', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_text1', 5, 0, 0, 1, 'Text 1', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_text2', 5, 0, 0, 1, 'Text 2', 0, '', 1000);
INSERT INTO `%prefix%fields` (`name`, `type`, `active`, `required`, `item_type`, `title`, `search`, `display`, `sort_order`) VALUES('ext_text3', 5, 0, 0, 1, 'Text 3', 0, '', 1000);
ALTER TABLE `%prefix%items` ADD `ext_int2` INT NULL AFTER `ext_int1`;
ALTER TABLE `%prefix%items` ADD `ext_int3` INT NULL AFTER `ext_int2`;
ALTER TABLE `%prefix%items` ADD `ext_double2` DOUBLE NULL AFTER `ext_double1`;
ALTER TABLE `%prefix%items` ADD `ext_double3` DOUBLE NULL AFTER `ext_double2`;
ALTER TABLE `%prefix%items` ADD `ext_varchar2` VARCHAR( 255 ) NULL AFTER `ext_varchar1`;
ALTER TABLE `%prefix%items` ADD `ext_varchar3` VARCHAR( 255 ) NULL AFTER `ext_varchar2`;
ALTER TABLE `%prefix%items` ADD `ext_datetime2` DATETIME NULL AFTER `ext_datetime1`;
ALTER TABLE `%prefix%items` ADD `ext_datetime3` DATETIME NULL AFTER `ext_datetime2`;
ALTER TABLE `%prefix%items` DROP INDEX `fulltext`, ADD FULLTEXT `fulltext` (`item_title`, `item_descr`, `item_descr_full`, `item_meta_keywords`, `item_meta_descr`, `link_url`, `ext_text1`, `ext_text2`, `ext_text3`, `ext_varchar1`, `ext_varchar2`, `ext_varchar3`);
