CREATE TABLE `%prefix%checklog` (`id` int(11) NOT NULL auto_increment, `date` datetime NOT NULL default '0000-00-00 00:00:00', `text` text NOT NULL, PRIMARY KEY  (`id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `%prefix%comments` (`id` int(11) NOT NULL auto_increment, `item_id` int(11) NOT NULL default '0', `user_id` int(11) NOT NULL default '0', `author_name` varchar(255) NOT NULL default '', `author_email` varchar(255) NOT NULL default '', `text` text NOT NULL, `vote` tinyint(4) NOT NULL default '0', `date_insert` datetime NOT NULL default '0000-00-00 00:00:00', `active` tinyint(4) NOT NULL default '0', `display` tinyint(4) NOT NULL default '0', PRIMARY KEY  (`id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8;
ALTER TABLE `%prefix%items` CHANGE `item_rating_users` `item_rating_users` DECIMAL( 6, 1 ) NOT NULL DEFAULT '0';
ALTER TABLE `%prefix%items` CHANGE `item_rating_users_neg` `item_rating_users_neg` DECIMAL( 6, 1 ) NOT NULL DEFAULT '0';
ALTER TABLE `%prefix%items` ADD `item_votes_count` MEDIUMINT NOT NULL DEFAULT '0' AFTER `item_rating_users_neg`;
ALTER TABLE `%prefix%items` ADD `item_com_count` MEDIUMINT NOT NULL DEFAULT '0' AFTER `item_votes_count`;
ALTER TABLE `%prefix%cats` ADD `link_count` INT NOT NULL DEFAULT '0' AFTER `item_count_full`;
ALTER TABLE `%prefix%cats` ADD `link_count_full` INT NOT NULL DEFAULT '0' AFTER `link_count`;
ALTER TABLE `%prefix%cats` ADD `article_count` INT NOT NULL DEFAULT '0' AFTER `link_count_full`;
ALTER TABLE `%prefix%cats` ADD `article_count_full` INT NOT NULL DEFAULT '0' AFTER `article_count`;
ALTER TABLE `%prefix%cats` ADD `last_update` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' AFTER `article_count_full`;
ALTER TABLE `%prefix%jumps` CHANGE `type` `type` ENUM( 'to', 'from', 'vote' ) NOT NULL DEFAULT 'to';
ALTER TABLE `%prefix%banners` ADD `on_cat_main` TINYINT NOT NULL DEFAULT '0' AFTER `child_cats`;
ALTER TABLE `%prefix%config` CHANGE `value` `value` TEXT DEFAULT NULL;
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('comments_links_enable', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('comments_articles_enable', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('comments_add_enable', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('comments_auto_approve', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('comments_min_author_name', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('comments_max_author_name', '50');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('comments_min_author_email', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('comments_max_author_email', '50');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('comments_min_text', '3');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('comments_max_text', '2000');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('cron_item_type', '');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('cron_item_status', '');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('cron_check_period', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('cron_check_limit', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('cron_password', '');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('comments_use_captcha', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('handle_not_exists', '0');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('statistics_enable', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('show_statistics', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('show_stats', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('rating_vote_limiter', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('rating_vote_interval', '3600');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('rating_enable', '1');
INSERT INTO `%prefix%config` (`name`, `value`) VALUES('rating_without_com', '1');
