presta_sitemap:
  resource: "@PrestaSitemapBundle/Resources/config/routing.yml"

default:
  resource: App\Controller\DefaultController
  type: annotation

smart_directory:
  resource: App\Controller\SmartDirectoryController
  type: annotation